apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  labels:
    app: fastapi
spec:
  # Тип Service, который мы будем использовать для Minikube:
  # NodePort открывает порт на самой хост-машине (твоей Ubuntu).
  type: NodePort
  
  # Селектор: ищет Pod'ы, у которых есть метка 'app: fastapi' (это наши два Pod'а Deployment).
  selector:
    app: fastapi
    
  # Правила перенаправления портов
  ports:
    - name: http
      # Порт, который будет открыт ВНУТРИ кластера (не трогать)
      port: 80 
      # Порт, который слушает наш FastAPI-контейнер (8000)
      targetPort: 8000 
      # Порт, который будет открыт на твоей Ubuntu-машине (случайный, >30000)
      # Minikube выберет его автоматически, но мы можем указать его. 
      # Мы узнаем точный порт на следующем шаге.
      # nodePort: 30007 # (Оставим K8s выбрать его, чтобы избежать конфликтов)