apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secrets
type: Opaque # Общий тип для ключей
data:
  # Название переменной окружения, которую будет читать контейнер
  # Значение ключа, закодированное в Base64
  # 'my-super-secret-key-for-fastapi' в Base64
  FASTAPI_SECRET_KEY: bXktc3VwZXItc2VjcmV0LWtleS1mb3ItZmFzdGFwaQo=
