

services:
  # 1. Сервис БЭКЕНДА (FastAPI)
  fastapi-app:
    # Dockerfile для этого сервиса находится в текущей папке (.).
    # Docker Compose сам соберет образ, если он еще не существует.
    build: . 
    # Сервис FastAPI слушает порт 8000 внутри приватной сети Docker.
    # Мы НЕ пробрасываем его на хост, чтобы он был доступен ТОЛЬКО для Nginx.
    expose:
      - 8000
   
    env_file:  # <-- НОВЫЙ БЛОК
      - .secrets

    volumes:
      - ./logs:/app/logs # Монтируем локальную папку 'logs' в контейнер как '/app/logs'  
    
    depends_on:
      db:
        condition: service_healthy # <-- Ждем, пока healthcheck БД станет успешным
    # Имя контейнера для удобства
    container_name: fastapi-backend

  # 2. Сервис ФРОНТЕНДА (Nginx Reverse Proxy)
  nginx-proxy:
    # Используем готовый официальный образ Nginx
    image: nginx:stable-alpine
    # Пробрасываем порт 80 Nginx на порт 80 хост-машины (Ubuntu)
    ports:
      - "80:80"
    # Копируем наш локальный конфиг Nginx внутрь контейнера
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # Nginx зависит от того, что fastapi-app будет запущен
    depends_on:
      - fastapi-app
    container_name: nginx-frontend

  db: # <--Новый сервис
      image: postgres:15-alpine
      env_file:
        - .secrets #передаем учетные данные
      volumes:
        - postgres_data:/var/lib/postgresql/data # Volume для сохранения данных БД
      restart: always

      # НОВЫЙ БЛОК: Проверка готовности (Healthcheck)
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
        interval: 5s
        timeout: 5s
        retries: 5
volumes:
  postgres_data: