apiVersion: v1
kind: Secret
metadata:
  name: github-deployer-token-manual
  annotations:
    # Важно: Привязываем этот Secret к Service Account, который мы создали
    kubernetes.io/service-account.name: github-deployer
type: kubernetes.io/service-account-token
